version: '3.8'

services:
  app:
    build:
      context: .
      args:
        REPO_URL: ${REPO_URL}
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_PASSWORD: ${GIT_PASSWORD}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - production

networks:
  production:
    external: true
